### ISSUE TITLE
git clone in README does not work

### ISSUE THREAD

**Issue by yschimpf** [hmxxu/BeatBuddy#40]
The git clone from the README resulted in a could not read from remote repository for me. A simple https clone from github worked. The expected behaviour would have been a successful clone instead of the error.

Simply enter the git clone command from the repository to reproduce it.

System: linux

**Comment by jly02** [comment]
Have you set up your SSH keys?

**Comment by jly02** [comment]
This is a non-issue. Make sure your [SSH keys are set](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).

**Comment by yschimpf** [comment]
You could still write a comment in the README. If you just provide the command I would expect it to work without any further setup. But maybe I am misunderstanding something.
