### ISSUE TITLE
npm start has compilation error (note npm version 8.19.2 was used)

### ISSUE THREAD

**Issue by yschimpf** [hmxxu/BeatBuddy#41]
I used the npm 8.19.2 which I am aware is not the required one. Still I wanted to report this as the bug could be based on smth. else and also a few warnings that look like potential code improvements are included

Result: 
Failed to compile.

Module not found: Error: Can't resolve 'fs' in '/homes/iws/yschimpf/Documents/swe/peer/BeatBuddy/node_modules/dotenv/lib'
WARNING in [eslint] 
src/Callback.ts
  Line 1:8:   'React' is defined but never used                                                                            @typescript-eslint/no-unused-vars
  Line 42:6:  React Hook useEffect has a missing dependency: 'navigate'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/Filter.tsx
  Line 5:27:    'useEffect' is defined but never used           @typescript-eslint/no-unused-vars
  Line 9:13:    'qs' is defined but never used                  @typescript-eslint/no-unused-vars
  Line 197:12:  'borderForFirstLast' is defined but never used  @typescript-eslint/no-unused-vars

src/components/GeneratedPlaylist.tsx
  Line 9:10:  'id' is defined but never used  @typescript-eslint/no-unused-vars
  Line 9:28:  'qs' is defined but never used  @typescript-eslint/no-unused-vars

src/components/PlaylistReady.tsx
  Line 5:14:   'qs' is defined but never used                   @typescript-eslint/no-unused-vars
  Line 7:10:   'returnDummyRec' is defined but never used       @typescript-eslint/no-unused-vars
  Line 23:10:  'decadeList' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/components/SearchBar.tsx
  Line 5:14:   'qs' is defined but never used                                                    @typescript-eslint/no-unused-vars
  Line 100:7:  Headings must have content and the content must be accessible by a screen reader  jsx-a11y/heading-has-content

src/components/SongResult.tsx
  Line 12:9:  'style' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/index.tsx
  Line 4:17:   'useState' is defined but never used       @typescript-eslint/no-unused-vars
  Line 9:14:   'qs' is defined but never used             @typescript-eslint/no-unused-vars
  Line 17:10:  'delayOverflow' is defined but never used  @typescript-eslint/no-unused-vars

src/utils.tsx
  Line 75:13:   Expected '===' and instead saw '=='                      eqeqeq
  Line 78:17:   Expected '===' and instead saw '=='                      eqeqeq
  Line 81:17:   Expected '===' and instead saw '=='                      eqeqeq
  Line 92:13:   Expected '===' and instead saw '=='                      eqeqeq
  Line 100:10:  'extractRGBValues' is defined but never used             @typescript-eslint/no-unused-vars
  Line 113:10:  'invertHex' is defined but never used                    @typescript-eslint/no-unused-vars
  Line 122:10:  'cClass' is defined but never used                       @typescript-eslint/no-unused-vars
  Line 157:7:   'count' is assigned a value but never used               @typescript-eslint/no-unused-vars
  Line 175:9:   'bodyLinearGradient' is assigned a value but never used  @typescript-eslint/no-unused-vars

ERROR in ./node_modules/dotenv/lib/main.js 24:11-24
Module not found: Error: Can't resolve 'fs' in '/homes/iws/yschimpf/Documents/swe/peer/BeatBuddy/node_modules/dotenv/lib'

ERROR in ./node_modules/dotenv/lib/main.js 25:13-28
Module not found: Error: Can't resolve 'path' in '/homes/iws/yschimpf/Documents/swe/peer/BeatBuddy/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/dotenv/lib/main.js 26:11-24
Module not found: Error: Can't resolve 'os' in '/homes/iws/yschimpf/Documents/swe/peer/BeatBuddy/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

webpack compiled with 3 errors and 1 warning
No issues found.

Expected result: Successfull build

Steps to reproduce: Follow the build steps from the developer documentation. Then in step 5 this happened on npm start.

OS: Linux. !! only version 8.19.2 for npm!! Correct version for node.

**Comment by jly02** [comment]
This issue is specifically due to breaking changes made in `npm` version 9.

**Comment by yschimpf** [comment]
Ok, thx for letting me know. I was expecting that but just wanted to let you know.
