### ISSUE TITLE
Tests: Typo in developer instructions or test file.

### ISSUE THREAD

**Issue by DreamRealitii** [hmxxu/BeatBuddy#42]
One of the tests fail because the one of the environment variables is named differently between the developer instructions and the EnvVars.test.ts file. The instructions use the name "REACT_APP_REDIRECT_URI", while the test file expects "REACT_APP_SPOTIFY_REDIRECT_URI".
![image](https://github.com/hmxxu/BeatBuddy/assets/33010927/358e7b3e-d195-413a-a953-0c99ca166c40)
![image](https://github.com/hmxxu/BeatBuddy/assets/33010927/112b9e6c-ba4f-4de9-bf22-3fff972ca7d8)

Reproduce: Run "npm run jest" in root directory.
System Info: OS = Windows 11, IDE = IntelliJ.

**Comment by jly02** [comment]
fixed
